name: OrderManagement

services:
  database:
    container_name: database
    image: postgres:14.5
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=ordermanagement
    ports:
      - 5432:5432
